name: lab2
version: 0.1.0.0
license: BSD-3-Clause
author: "Aigul Ibraimova"
copyright: "2025 Aigul Ibraimova"

extra-source-files:
  - README.md

dependencies:
  - base >= 4.7 && < 5
  - HUnit
  - vector

ghc-options:
  - -Wall

library:
  source-dirs: src

# executables:
#   lab2-exe:
#     main: Main.hs
#     source-dirs: app
#     ghc-options:
#       - -threaded
#       - -rtsopts
#       - -with-rtsopts=-N
#     dependencies:
#       - base

tests:
  lab2-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -Wall
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - lab2
      - HUnit
      - QuickCheck

build-tools:
  - hlint
  - ormolu
